apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part: modern-service

namePrefix: modern-

resources:
  - deployment.yaml
  - service.yaml

vars:
  - name: MODERN_SERVICE_NAME
    objref:
      name: service
      kind: Service
      apiVersion: v1
