apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part: nginx

namePrefix: nginx-
namespace: ingress-nginx

resources:
  - ingress.yaml

configurations:
  - kustomize-config.yaml

secretGenerator:
  - name: tls-certificate
    files:
      - certificate/ca.pem
      - certificate/server.pem
      - certificate/server-key.pem
