apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part: legacy-service

namePrefix: legacy-

resources:
  - deployment.yaml
  - service.yaml

vars:
  - name: LEGACY_SERVICE_NAME
    objref:
      name: service
      kind: Service
      apiVersion: v1
