apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wirepact-poc-showcase

commonLabels:
  app.kubernetes.io/part-of: wirepact-poc-showcase

resources:
  - namespace.yaml
  - legacy-service
  - modern-service
  - frontend
  - ambassador
#  - nginx

vars:
  - name: NAMESPACE
    objref:
      apiVersion: v1
      kind: Namespace
      name: wirepact-poc-showcase

configMapGenerator:
  - name: modern-service-config
    literals:
      - USE_WIREPACT=false

images:
  - name: frontend
  - name: modern
  - name: legacy
